### ISSUE TITLE
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by Frank-Dz** [rish-16/tokenlearner-pytorch#4]
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

**Comment by ahmadmobeen** [comment]
change the [line 33](https://github.com/rish-16/tokenlearner-pytorch/blob/a6908107c5b53b837127806fc1d46c64694bffc5/tokenlearner_pytorch/tokenlearner_pytorch.py#L33) in tokenlearner_pytorch.py as follows:

`self.tokenizers = [SpatialAttention() for _ in range(S)] '
->
'self.tokenizers = nn.ModuleList([SpatialAttention() for _ in range(S)])`
